### ISSUE TITLE
Upgrading to Python 3.8

### ISSUE THREAD

**Issue by brandon-feder** [chime-frb-open-data/chime-frb-open-data.github.io#3]
Hello. I was simply wondering if there were any plans to upgrade this package to python 3.8 now that 2.7 is no longer supported and msgpack is deprecated.

**Comment by shinybrar** [comment]
@brandon-feder Hi, sorry about the late response. I think that is a fair request and I can look into updating the code -- and I think you mean the python `cfod` package?
